### ISSUE TITLE
About paper

### ISSUE THREAD

**Issue by Xinyi-Ning** [verlab/Structural_Reasoning_SRR#1]
Hello blogger, has this paper been published yet? I can't find this paper, so I was wondering if you could send it to me for reference，thanku very much

**Comment by daviduarte** [comment]
I found only the master thesis at **https://repositorio.ufmg.br/handle/1843/45142**.

**Comment by eduardoatr** [comment]
Thanks for your interest in our paper. We have submitted the revised version, and I will update the repository as soon as we have an answer. Meanwhile, you can refer to my master's thesis, as pointed out by @daviduarte.

**Comment by Xinyi-Ning** [comment]
thanku！

**Comment by eduardoatr** [comment]
The paper was accepted! You can use [this link](https://authors.elsevier.com/c/1hTvU3qy-3aj0o) to download the final version. Thanks again for your interest, and consider citing us if this repository was helpful to you. 😁

**Comment by Xinyi-Ning** [comment]
thanku！
