### ISSUE TITLE
PIPA Dataset link failed

### ISSUE THREAD

**Issue by Xinyi-Ning** [verlab/Structural_Reasoning_SRR#2]
Dataset link failed
People in Photo Album (PIPA) dataset The link to this dataset is invalid. Please ask the blogger to update the method of obtaining the dataset

**Comment by eduardoatr** [comment]
Unfortunately, the dataset has been pulled from the internet, and I am still trying to figure out why. The last working [snapshot](https://web.archive.org/web/20200316165359/https://people.eecs.berkeley.edu/~nzhang/piper.html) at the WayBackMachine is from March 16, 2020. I might have a copy of the original data, but I am not sure if I can distribute it. For now, you can try a workaround that I have added to the description of the project, and I will see if I can find and upload the dataset somewhere.

**Comment by Xinyi-Ning** [comment]
got it, thanku

**Comment by eduardoatr** [comment]
If you are still interested, I've uploaded an intact copy of the original PIPA dataset to Google Drive and added a link to the README.md file.
