### ISSUE TITLE
Protocols not found

### ISSUE THREAD

**Issue by IsabelJimenez99** [verlab/Structural_Reasoning_SRR#4]
I have tried to search for the protocols for the [Individual Age/Gender/Clothing Features](https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/human-activity-recognition/social-relation-recognition) feature extraction models but I can't find anything but the models with different names. What am I supposed to do?

**Comment by eduardoatr** [comment]
All the models and protocols are bundled together into the `trained_models.zip` file. More specifically, you can find the double-stream CaffeNet protocols in the `/trained_models/caffeNet_models/end_to_end_training_prototxt` folder. Use the `test_net.prototxt`, and don't forget to adjust the input and output layer according to what is defined into the extraction scripts.
